#!/usr/bin/env python3
"""Generate voice-map outputs from data/phonetic_training/morae/good/.

This is the single source of truth for the hiragana ↔ kunrei mapping and the
WAV directory walk. Produces two files:

    worker/src/voicemap.js   — JS module the worker imports to resolve
                                (mora, idx) → voice name at INSERT time.
    build/voices.json        — JSON manifest for downstream build scripts
                                (transcode_audio.py constructs WAV paths
                                from it, build.py reads voices for the
                                window.VOICE_COUNTS / window.VOICE_MAP
                                injections). Schema:
                                  {
                                    "<kunrei>": {
                                      "hiragana": "<hira>",
                                      "voices": ["<stem1>", "<stem2>", ...]
                                    },
                                    ...
                                  }

idx ordering is alphabetical (`sorted(wavs)`). Re-running after voice changes
shifts idx values for historical events — see worker/README for the implications.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MORAE_GOOD = ROOT / "data" / "phonetic_training" / "morae" / "good"
BUILD = ROOT / "build"
WORKER = ROOT / "worker"

# Hiragana → (kunrei, vowel). kunrei stays ASCII so audio/ URLs and DB rows
# don't need percent-encoding. The vowel is just kunrei[-1], so we recompute
# it downstream rather than carry it in voices.json.
MORAE = {
    "さ": ("sa", "a"), "ざ": ("za", "a"),
    "しゃ": ("sya", "a"), "じゃ": ("zya", "a"), "ちゃ": ("tya", "a"),
    "し": ("si", "i"), "じ": ("zi", "i"), "ち": ("ti", "i"),
    "す": ("su", "u"), "ず": ("zu", "u"), "つ": ("tu", "u"),
    "しゅ": ("syu", "u"), "じゅ": ("zyu", "u"), "ちゅ": ("tyu", "u"),
    "そ": ("so", "o"), "ぞ": ("zo", "o"),
    "しょ": ("syo", "o"), "じょ": ("zyo", "o"), "ちょ": ("tyo", "o"),
}


def build_voicemap() -> dict[str, dict]:
    out: dict[str, dict] = {}
    for mora_dir in sorted(MORAE_GOOD.iterdir()):
        if not mora_dir.is_dir():
            continue
        entry = MORAE.get(mora_dir.name)
        if not entry:
            continue
        kunrei, _ = entry
        wavs = sorted(p.stem for p in mora_dir.iterdir() if p.name.endswith(".wav"))
        out[kunrei] = {"hiragana": mora_dir.name, "voices": wavs}
    return out


def write_voicemap_js(data: dict[str, dict]) -> None:
    just_voices = {k: v["voices"] for k, v in data.items()}
    body = json.dumps(just_voices, ensure_ascii=False, indent=2)
    (WORKER / "src" / "voicemap.js").write_text(
        "// Auto-generated by scripts/voicemap.py — do not edit by hand.\n"
        "// (mora, idx) → voice name. The build is authoritative; if voices\n"
        "// change, re-run scripts/voicemap.py and redeploy the worker.\n\n"
        f"export const VOICE_MAP = {body};\n\n"
        "export function nameOf(mora, idx) {\n"
        "  const arr = VOICE_MAP[mora];\n"
        "  return arr && idx >= 0 && idx < arr.length ? arr[idx] : null;\n"
        "}\n",
        encoding="utf-8",
    )


def write_voices_json(data: dict[str, dict]) -> None:
    BUILD.mkdir(parents=True, exist_ok=True)
    (BUILD / "voices.json").write_text(
        json.dumps(data, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def main() -> None:
    data = build_voicemap()
    if not data:
        import sys
        sys.exit(f"No voices found under {MORAE_GOOD.relative_to(ROOT)}/.")
    write_voicemap_js(data)
    write_voices_json(data)
    total = sum(len(v["voices"]) for v in data.values())
    print(f"voicemap: {len(data)} morae · {total} voices → worker/src/voicemap.js + build/voices.json")


if __name__ == "__main__":
    main()
